---------------------------------------------------
--Project: 0911
--By: fatemeh.torabi@swansea.ac.uk
--Aim: create RRDA for WDDS
---------------------------------------------------
/*
CREATE TABLE SAILW0911V.RRDA_WDDS AS 
(
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
	FETCH FIRST 2 ROWS ONLY
)WITH NO DATA;
*/

TRUNCATE TABLE SAILW0911V.RRDA_WDDS IMMEDIATE;

ALTER TABLE SAILW0911V.RRDA_WDDS ACTIVATE NOT LOGGED INITIALLY;

--Update: you may require to add some insert statements- check below the latest year and month and update based on most recent release availability 
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2022' AND MONTH(DT_PRESCRIBED)='1';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='12';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='11';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='10';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='9';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='8';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='7';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='6';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='5';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='4';

INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='3';

INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='2';

INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2021' AND MONTH(DT_PRESCRIBED)='1';

INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
	
--2020	
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='1';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='2';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='3';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='4';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='5';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='6';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='7';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='8';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='9';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='10';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='11';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2020' AND MONTH(DT_PRESCRIBED)='12';

---2019
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='1';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='2';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='3';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='4';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='5';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='6';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='7';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='8';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='9';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='10';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='11';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2019' AND MONTH(DT_PRESCRIBED)='12';

--2018
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='1';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='2';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='3';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='4';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='5';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='6';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='7';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='8';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='9';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='10';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='11';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2018'AND MONTH(DT_PRESCRIBED)='12';

INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
	
---2017	
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='1';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='2';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='3';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='4';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='5';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='6';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='7';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='8';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='9';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='10';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='11';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2017'AND MONTH(DT_PRESCRIBED)='12';

---2016

INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='1';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='2';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='3';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='4';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='5';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='6';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='7';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='8';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='9';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='10';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='11';
INSERT INTO SAILW0911V.RRDA_WDDS 
	SELECT DISTINCT ALF_E , DT_PRESCRIBED,  PRAC_CD_E ,DMDCODE_PRESCRIBED , PRODUCT_PRESCRIBED,
	QTY_PRESCRIBED ,QTY_PRESCRIBED_VAL , QTY_UOM_CODE, MONTH_DISPENSED, DISPENSER_ID, FORM_NO, 
	DMD_CD_WDDS, BNF_COMBINED, BNF_COMBINED_DESC, DMD_CD_BSA,DMD_DESC_BSA,DMD_DESC_UKHDV, BNF_NAME_BSA,  BNF_UKHDV, BNF_UPDATED_UKHDV, BNF_SUBPARAGRAPH,
	AVAIL_FROM_DT
	FROM SAILW0911V.STAGED_TAB6_ALF
WHERE ALF_E IS NOT NULL AND YEAR(DT_PRESCRIBED)='2016'AND MONTH(DT_PRESCRIBED)='12';

COMMIT;

SELECT COUNT(*), count(DISTINCT ALF_E ), count(DISTINCT DMDCODE_PRESCRIBED ), count(DISTINCT BNF_COMBINED ) FROM SAILW0911V.RRDA_WDDS;
--run=Jan 2022: coverage=Nov 2021: 777350132	3258065	30662	22039
--Run=Mar 2022: coverage=Dec 2021:

SELECT count(DISTINCT DMDCODE_PRESCRIBED ), count(DISTINCT BNF_COMBINED ) FROM SAILW0911V.RRDA_WDDS
WHERE BNF_COMBINED IS NOT NULL;

DROP TABLE SAILW0911V.STAGED_TAB1;
DROP TABLE SAILW0911V.STAGED_TAB2;
DROP TABLE SAILW0911V.STAGED_TAB3;
DROP TABLE SAILW0911V.STAGED_TAB4;
DROP TABLE SAILW0911V.STAGED_TAB5;
DROP TABLE SAILW0911V.STAGED_TAB6;
DROP TABLE SAILW0911V.STAGED_TAB6_ALF;